title: Yang Lin's Homepage
page-top-title: Nova_leo
top-section-bg-text: Never stop
home-subtitle: Nova_leo&ensp;|&ensp;林阳
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
site_name: "Novaleo"
site_description: "大模型算法蒟蒻 | AI agent researcher"
email: "15062791135@163.com"
